services:
  webrtc_platform:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARCH: amd64
        ROS_DISTRO: humble
        CMAKE_VERSION: 3.30.1
        BUILD_TYPE: Release
    command: tail -f /dev/null

networks:
  dockerNet:
    driver: bridge
